### ISSUE TITLE
help with debugging on chrome

### ISSUE THREAD

**Issue by Turqueso** [floridoo/gulp-sourcemaps#140]
**Update:** Seems to work on fine on mac, but not on windows  I've enabled source maps on chrome but I can't make it work.

This is my task
```
gulp.task('styles', function(){
  gulp.src(['./html/sass/**/*.scss'])
    .pipe(plumber({
    errorHandler: function (error) {
      console.log(error.message);
      this.emit('end');
    }}))
    .pipe(sourcemaps.init())
    .pipe(sass())
    .pipe(autoprefixer({browsers: ['last 2 versions']}))
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest('html/css/'))
    .pipe(browserSync.reload({stream:true}))
});
```

![image](https://cloud.githubusercontent.com/assets/4932347/8537437/29cb6f88-241c-11e5-987e-e65d2f34dd2c.png)  ![image](https://cloud.githubusercontent.com/assets/4932347/8537443/3fadb7b6-241c-11e5-9721-394219255fd0.png)

**Comment by alx-khramov** [comment]
I have the same task and the same problem. I've also tried to run task on ubuntu and sourcemaps worked fine, but not on Win7.

**Comment by Turqueso** [comment]
I'm on win 8.1

**Comment by JohnHeroHD** [comment]
I've got the same issue, and indeed, my collegues on Mac have no issues. But on Windows 7 it's not working.

**Comment by kyaido** [comment]
Are you using an older version gulp-sass?
Please try new version gulp-sass because problem on Windows has been resolved in version 2.0.4.

**Comment by alx-khramov** [comment]
@kyaido thanks a lot, that partially solved the issue for me. Now I guess gulp-minify-css breaks my sourcemaps. Anyway, thanks.

**Comment by kyaido** [comment]
@alx-khramov I have the same problem.
Try `{advanced:false}` option with gulp-minify-css.
Maybe the problem to solve but I don't know why the problem is solved.

**Comment by alx-khramov** [comment]
@kyaido Thanks, that really helped. But I think i will move my building process from Windows to vagrant machine with unix-system installed, because I don't want to face such problems with Win support in the future.
